# @Author: JanKinCai
# @Date:   2019-12-12 21:10:00
# @Last Modified by:   JanKinCai
# @Last Modified time: 2019-12-12 21:10:00
language: python

dist: bionic
sudo: required

python:
  - 3.7
  - 3.6
  - 3.5

install:
  - pip install -U tox-travis

script: tox
